[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iam"
version = "0.1.0"
dependencies = ["torch>=2.0.0", "numpy>=1.21.0"]

[tool.setuptools]
packages = ["iam"]
package-dir = {"" = "python"}
